#!/usr/bin/env zsh
#
# Usually, this file is sourced by ~/.zshrc, but it is also marked as
# executable for testing.

zmodload zsh/datetime

# TODO: figure out how to turn these into variables

last_update='last_update'
last_init='last_init'

function _current_epoch() {
  echo $(( $EPOCHSECONDS / 60 / 60 / 24 ))
}

function _update_last_updated() {
  echo "UPDATED=$(_current_epoch)" >! "last_updated"
}

function _run_scripts() {

  local dir=$1
  local os=$2
  local base=""
  local tmp=""
  local target="#"

  if [ -d "$dir" ] && [ ! -z "$(ls "$dir"/)" ]; then
    for file in "$dir"/*; do
      base=${file##*/}
      tmp=${base#*-}
      target=${tmp%%-*}

      # skip improperly formated files, like README.
      if [[ "$target" != "$base"  ]]; then

        if [[ "$target" == "all" ]] ||
           [[ "$target" == "$os" ]] ||
           [[ "$target" == "$HOSTNAME" ]]; then
          source "$file"
        fi
      fi
    done
  fi
}

# _run_locked_scripts is used for daily, weekly, and monthly scripts.  We use
# a lock here because these will likely take some time to execute, but there
# is still a chance of a race condition.  (Though, it is extremely unlikely
# since these scripts don't run without a user response to a prompt.
function _run_locked_scripts() {

  local dir=$1
  local os=$2
  local base=""
  local tmp=""
  local target="#"

  # timed scripts cannot overlap. note that there is a small risk from a
  # race condition here
  declare -r lock_file="startup.lock"

  trap "{ rm -f lock_file }" SIGINT SIGTERM

  if [ ! -f "$lock_file" ]; then

    touch "$lock_file"

    echo "** Running $dir scripts **"

    if [ -d "$dir" ] && [ ! -z "$(ls "$dir"/)" ]; then
      for file in "$dir"/*; do
        base=${file##*/}
        tmp=${base#*-}
        target=${tmp%%-*}

        # skip improperly formated files, like README.
        if [[ "$target" != "$base"  ]]; then

          if [[ "$target" == "all" ]] ||
             [[ "$target" == "$os" ]] ||
             [[ "$target" == "$HOSTNAME" ]]; then
            source "$file"
          fi
        fi
      done
    fi
    rm "$lock_file"
  else
    echo "Another startup detected.  Skipping this run."
  fi
}

# Prompt for updates and run them
function _prompt_for_updates() {
  local os=$1

  if [ -f "last_update" ]
  then
    source "last_update"

    # if $last_update was empty, update it
    if [[ -z "$UPDATED" ]]; then
      _update_last_updated && return 0;
    fi

    epoch_diff=$(($(_current_epoch) - $UPDATED))
    if [ $epoch_diff -gt 1 ]
    then
      echo "[UPDATES] Would you like to update stuff? [Y/n]: \c"
      read line
      if [[ "$line" == Y* ]] || [[ "$line" == y* ]] || [ -z "$line" ]; then
        _run_locked_scripts "update" "$os"
      fi
    fi
  fi
  _update_last_updated
}

# save off the current directory
pushd . > /dev/null
cd  $HOME/.zsh

# set env vars for script selection
export OS=`uname -s`
export ARCH=`uname -m`

# get abreviated os name for script matches
abrevOS="unknown"
case $OS in
    "Darwin")
        abrevOS="osx";;
    "Linux")
        abrevOS="lnx";;
    "FreeBSD")
        abrevOS="bsd";;
    "Minux")
        abrevOS="mnx";;
esac

# source the run-always modular startup scripts
_run_scripts "always" "$abrevOS"

# cancel upgrade if the current user doesn't have write permissions for the
# current directory.
[[ -w "$(pwd)" ]] || return 0

# cancel upgrade if these tools are unavailable on the system
# TODO: It would be ideal to print an error message here
whence git >/dev/null || return 0
whence brew >/dev/null || return 0
whence pandoc >/dev/null || return 0
whence tlmgr >/dev/null || return 0
whence vim >/dev/null || return 0

_prompt_for_updates "$abrevOS"

# restore the original directory
popd > /dev/null
